### ISSUE TITLE
Ability to toggle organizer/kick yourself leaving no one in your place

### ISSUE THREAD

**Issue by kythre** [MarkMichon1/groupbuyorganizer2#2]
I created a new event then toggled organizer on myself and now I believe there isn't anyone able to control the event, aside from an site admin I'd assume.

I created a new group and attempted to remove myself but I got an error page similar to https://github.com/MarkMichon1/groupbuyorganizer2/issues/1, except the URL was
```/events/04385f20-ae47-486c-b4a6-c0e30f3aa696/remove-participant/002b5485-5eba-4786-b130-d1fcaa275993/```
and the traceback ended with
``` 
 File "/home/mark7/gb/events/views.py", line 538, in remove_participant
    for commit in target_membership.split_commits:
```

The event I toggled my organizer role on:
https://www.pyrogroupbuys.com/events/6294735a-7646-46c1-981b-f311138f9227/

**Comment by MarkMichon1** [comment]
Testing indicates this is fixed.  All it took was a small change in logic in the template.
