### ISSUE TITLE
"You must be an organizer" when I am an organizer and "all event order visibility" disabled

### ISSUE THREAD

**Issue by kythre** [MarkMichon1/groupbuyorganizer2#4]
I created a new group,
disabled "Allow users to see all event order data (summary, orders of others)", 
clicked either "Order Summary" or "User Breakdown", 
and finally I was taken back to the main page with the message "Allow users to see all event order data (summary, orders of others)". 
I am an organizer on a freshly created group (empty aside from myself)

**Comment by MarkMichon1** [comment]
Hey Kyle, thanks for raising these issues.  After looking at all of them, I can already tell most of them are one line fixes, while others need a bit closer of a look.  The current github branch completely breaks the app- I'm adding quite a bit of functionality and redoing the existing to account for React.js integration.  However, I was going to keep the site up in its current state until those changes were complete.  Tonight I'm going to make all of these fixes on the server code, and update these issues accordingly.

Mark Michon

**Comment by kythre** [comment]
Cool, sounds good. I hope I'm not being annoying by creating so many broken events and posting these all in different threads. I suppose I'll stop trying to break everything at least until the next update rolls out.

**Comment by MarkMichon1** [comment]
Nah, I appreciate you finding these... otherwise it would've remained this way for the duration of me finishing this overhaul.

**Comment by kythre** [comment]
I figure better me then someone malicious and later on during actual use. Justification for abusing a developing website lol

**Comment by MarkMichon1** [comment]
Fine by me lol, this is a learning experience.  The service may be down for a couple days as I now have something to fix with the DB, and I am pretty stretched on time to fix this.  Thanks again Kyle... fixed.
